sudo: required
services:
  - docker

before_install:
  - docker build -t asafmoalem/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asafmoalem/docker-react npm run test -- --coverage